name: Release to Puppet Forge

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build Puppet module
      run: |
        bundle exec rake build

    - name: Publish to Puppet Forge
      env:
        PDK_FORGE_TOKEN: ${{ secrets.PUPPET_FORGE_API_KEY }}
      run: |
        bundle exec puppet module release pkg/*.tar.gz --forge-token $PDK_FORGE_TOKEN
